services:
  # Server itself (CPP)
  app:
    build:
      context: ./server_cpp
      dockerfile: Dockerfile
    container_name: gmail_app
    stdin_open: true     # <-- keeps stdin open
    tty: true            # <-- allocates a pseudo-TTY
    volumes:
      - app_data:/usr/src/app  # <-- only the "data" folder is persisted between runs
    ports:
      - "42069:42069"
  # Server gtest
  gtest:
    build:
      context: ./server_cpp
      dockerfile: Dockerfile.test
    container_name: gmail_tests
    # Prevent the use of terminal input during test runs
    stdin_open: false
    tty: false
  # Client (Python)
  python_client:
    build:
      context: ./client_python
      dockerfile: Dockerfile
    container_name: python_client
    depends_on:
      - app
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=app
      - SERVER_PORT=42069
    # Change 'app' to desired server name here, '42069' to desired port (given as args)
    command: [ "python", "main.py", "app", "42069" ]
  # Client test runner (Python).
  test_client:
    build:
      context: .
      dockerfile: client_python/Dockerfile.tests
    container_name: client-tests
    depends_on:
      - app
    command: ["python","client_python/tests/test_client_unittest.py"] 
  

volumes:
  app_data:   # <-- define the named volume