services:
  # React frontend
  web_front:
    profiles: ["web_app"]
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    depends_on:
      - web_server
    ports:
      - "3000:3000"
    networks:
      - gmail-net

  # Web server using JS express
  web_server:
    profiles: ["web_app"]
    build:
      context: ./web_server
      dockerfile: Dockerfile
    container_name: web_server
    env_file:
      - ./web_server/.env
    depends_on:
      - run_server
    ports:
      - "${NODE_PORT:-3001}:3001"
    networks:
      - gmail-net

  # Server itself (CPP)
  run_server:
    profiles: ["web_app", "tests"]
    build:
      context: ./server_cpp
      dockerfile: Dockerfile
    container_name: gmail_server
    stdin_open: true     # <-- keeps stdin open
    tty: true            # <-- allocates a pseudo-TTY
    volumes:
      - app_data:/usr/src/run_server  # <-- only the "data" folder is persisted between runs
    ports:
      - "12347:12347"
    networks:
      - gmail-net

  # Server gtest
  gtest:
    profiles: [ "tests" ]
    build:
      context: ./server_cpp
      dockerfile: Dockerfile_test
    container_name: gmail_tests
    # Prevent the use of terminal input during test runs
    stdin_open: false
    tty: false

  # Client (Python)
  python_client:
    profiles: [ "client" ]
    build:
      context: ./python_client
      dockerfile: Dockerfile
    # container_name: python_client
    depends_on:
      - run_server
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=run_server
      - SERVER_PORT=12347
      - PYTHON=/python_client
    command: [ "python", "main.py", "run_server", "12347" ]
    networks:
      - gmail-net

  # Client test runner (Python).
  test_client:
    profiles: [ "tests" ]
    build:
      context: ./python_client
      dockerfile: Dockerfile.tests
    container_name: client_tests
    depends_on:
      - run_server
    command: ["python","tests/test_client_unittest.py"]


volumes:
  app_data:

networks:
  gmail-net: