# This dockerfile is for solely running tests of .cpp files
# Author: Yuval Anteby

# Use the official GCC image from Docker
FROM gcc:latest

# Add CMake to the container
RUN apt-get update && apt-get install -y cmake

# Copy and set the project in the container
WORKDIR /usr/src/server_tests
COPY server_cpp ./
# Ensures a clean build folder
RUN rm -rf build && mkdir build
WORKDIR /usr/src/server_tests/build

# Compile the CPP tests, add more files and flags as needed
RUN cmake .. && make

# Run the tests
CMD ["./runTests"]