# use official python image 
FROM python3.11-slim

# set working directory 
WORKDIR /app/src

# copy only whats needrd for testing 
COPY  client_python ./client_python

# Dfault command: run test 
CMD [ "python","client_python/tests/test_client_unittest.py" ]