name: CI

# Trigger only 
on:
  pull_request:
    paths-ignore:
      - '**.md' # Ignore changes to README files - no need to recheck the code
    branches:
      - main
      - main-Ex2
      - main-Ex3
      - main-Ex4
      - main-Ex5
      - GA-36-Client-side
      - GA-29-TCP-connection-C-server
      # TODO: Add more main-ExN branches as we need for assignments
    
jobs:
  # ----- Build & tests the CPP server -----
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and run gtests
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            --target gtest \
            --file server_cpp/Dockerfile_test \
            --load \
            -t gmail_tests \
            .
          docker run --rm gmail_tests
      
