name: CI

# Trigger only 
on:
  pull_request:
    paths-ignore:
      - '**.md' # Ignore changes to README files - no need to recheck the code
    branches:
      - main
      - main-Ex2
      - main-Ex3
      - main-Ex4
      - main-Ex5
      - GA-36-Client-side
      - GA-29-TCP-connection-C-server
      # TODO: Add more main-ExN branches as we need for assignments
    
jobs:
  # ----- Build & tests the CPP server -----
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and run gtests
        run: docker compose run --build --rm gtest
        
  # ----- Build the Python client -----
  build-python-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Python client
        run: docker build -t python-client ./client_python

      - name: Run client (smoke test with dummy input)
        run: docker run --rm python-client python src/main.py 127.0.0.1 42069 || true # Put or true since it's not a requirement to pass tests on client yet
